name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2
      - run: bun install
        working-directory: ./open-vscode-remote
      - run: bun run build
        working-directory: ./open-vscode-remote
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./open-vscode-remote/dist/
  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
